rules:
  clean-import-paths: 0
  class-name-format: 0
  no-important: 0
  variable-name-format: 0
  placeholder-name-format: 0
  no-url-domains: 0
  no-url-protocols: 0
  indentation:
    - 2
    - size: tab
  hex-length:
    - 2
    - style: long
  mixin-name-format:
    - 2
    - convention: camelcase
  nesting-depth:
    - 1
    - max-depth: 4
